label: firebase_push_notifications

admin: [0.0.0.0, 3001]
admin-insecure-mode: true
# admin-api-key: change-me

inbound-transport:
  - [http, 0.0.0.0, 3000]
  - [ws, 0.0.0.0, 3002]
outbound-transport: http
endpoint:
  - http://host.docker.internal:3000

plugin:
  - firebase_push_notifications.v1_0

genesis-url: http://test.bcovrin.vonx.io/genesis

log-level: info

# Connections
debug-connections: true
auto-accept-invites: true
auto-respond-messages: true
auto-ping-connection: true
auto-accept-requests: true

# Invitation
invite-label: "Mediator"
invite-multi-use: true

# Mediation
open-mediation: true
enable-undelivered-queue: true
