label: multitenant_provider

auto-provision: true

# Admin
admin: [0.0.0.0, 3001]
admin-insecure-mode: true
# admin-api-key: change-me

# Transport
inbound-transport:
  - [http, 0.0.0.0, 3000]
  - [ws, 0.0.0.0, 3002]
outbound-transport: http
endpoint:
  - http://host.docker.internal:3000

# plugins
plugin:
  - multitenant_provider.v1_0

plugin-config-value:
  - multitenant_provider.manager.class_name="multitenant_provider.v1_0.manager.AskarMultitokenMultitenantManager"
  - multitenant_provider.manager.always_check_provided_wallet_key=true
  - multitenant_provider.errors.on_unneeded_wallet_key=false

#config
genesis-url: http://test.bcovrin.vonx.io/genesis

# Wallet
wallet-type: askar
wallet-storage-type: default
wallet-name: test-provider-wallet
wallet-key: test-provider-key

# Multi-tenancy
multitenant: true
jwt-secret: insecure-jwt-secret
multitenant-admin: true

log-level: info

auto-accept-invites: true
auto-respond-messages: true
