name: sync-fork
on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: write-all
      # contents: write
      # pull-requests: write
      # repository-projects: write
      # actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync repository with the upstream
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          DEBUG=1 gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Send notification on sync failure
        if: failure()
        uses: ./.github/workflows/actions/send-slack-notification
        with:
          slack_notification: "Unable to sync the repository with its upstream. See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} for more information."
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
